[package]
authors = ["Pollen Robotics <contact@pollen-robotics.com>"]
name = "electric_dog"
version = "0.1.0"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.luos]
path = "../luos"

[dependencies.mockup_hal]
git = "https://github.com/pollen/stm32-mockup-hal/"
